matrix:
  include:
  - language: go
    sudo: required
    services:
      - docker
    before_script: cd backend
    script:
      - export GO111MODULE=on
      - go mod vendor
      - make build
      - test -f bin/linux_amd64/blog_backend
      - make all-container
      - docker images | grep "^martinheinz/blog_backend.*__linux_amd64"
      - make test

  - language: node_js
    node_js:
      - "node"
    script:
      - docker build -t blog-frontend ./frontend
  - language: go
    addons:
      sonarcloud:
        organization: martinheinz-github
        token:
          secure: "hbGHoYneczpzXmgBLoSKDNEXH7Gv2FVI7LGyHGXdUq3qdaJfRPzDcnMneBNwOl9/5tYYtbtx5uL9xuMa7VFzvosFhiszb8zEpPEAhUQ7jUYS/6Zchvsb5GgGhb8kk2Zud4UpoRbNr8iaqU6LCbxjMGx/SJkvyqMsMjX5zudMuV3OwRlX7JbsLrENdcb6S0PJAMknNRNEZoVjJ8uuJ0MPFb8fns19CnkiBylY64fUPzdiEh7CRSaxI5CbsNxTRZl4gjEPf3orlnHrMG/HhxOZ2PcCaLpW7+aZjQUd0RTYyOmX4u330tzQyCmTCFlG3Kl/XcDSGGBIGYcTzMAStfZ84NByV3e3jKEXesaXSfsCGZZqFbOtqWAEA60bBRyZFjkNIUUH1+uH3EcKaiQNPdbn46M7gnW4nwHlI7gpkCL2oDMJpHh7DcBDDc0ZtzSrN7lUzYO6M+i+8Xf4O/xnwmNJH0NHXZ9dCnQCfzlLLoFtXkflmMpu7apLiLKD6fdcQbatbu189sAiDJwxx4ehTI+zKCYfyf+exu/T8DaZtzctNh4fZ1NbXkhBFPlVf+++PXXiAWlK7nN6lhe15LAS50ZSmP2rjjScQKoh6F1WrROreguWNZdOlG58FH2Cxno7xb3h0yoGVRfA6hhlw5GQv62Lk3ykzzzfSWywEkHt6nnNPsc="
    before_script:
    - cd backend
    - export GO111MODULE=on
    - go mod vendor
    - make test
    - cd ..
    script:
    - sonar-scanner

notifications:
  email: false