version: '3.7'
services:
  backend:
    image: ghcr.io/martinheinz/blog_backend
    container_name: blog_backend
    healthcheck:
        test: ["CMD", "curl", "-f", "backend"]
        interval: 30s
        timeout: 10s
        retries: 5
    depends_on:
      - blog_db
    ports:
      - 8080:8080
      - 9080:9080
    volumes:
      - ./data/certbot/conf/live/${HOST}:/etc/certs

  blog_db:
    image: martinheinz/blog_db:latest
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    container_name: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      DB_NAME: "blog"
      POSTGRES_DB: blog
      PGPORT: 5432
      POPULATE_DB: ${POPULATE_DB}

volumes:
  data: {}
